# docker-compose.yml
services:
  # Serwis bazy danych PostgreSQL
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=phishquiz_db
      - POSTGRES_USER=phishquiz_user
      - POSTGRES_PASSWORD=phishquiz_password
    restart: always

  # Serwis aplikacji Django
  web:
    build: .
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    expose:
      - 8000
    depends_on:
      - db
    environment:
      - DB_NAME=phishquiz_db
      - DB_USER=phishquiz_user
      - DB_PASSWORD=phishquiz_password
      - DB_HOST=db
      - DB_PORT=5432
    restart: always

  # Serwis Nginx
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    depends_on:
      - web
    restart: always

# Definicja wolumenów do przechowywania danych
volumes:
  postgres_data:
  static_volume: