# Generated by Django 5.2.5 on 2025-08-18 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_url', models.URLField(help_text='The legitimate URL.', max_length=500)),
                ('phishing_url_1', models.URLField(help_text='A phishing URL.', max_length=500)),
                ('phishing_url_2', models.URLField(help_text='Another phishing URL.', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
